// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarROnSmiCyYHq__1hp2Ua_Zw7auln7rA',
    appId: '1:1046855873659:web:37563a9569056f0b155ede',
    messagingSenderId: '1046855873659',
    projectId: 'unirent-18b7b',
    authDomain: 'unirent-18b7b.firebaseapp.com',
    storageBucket: 'unirent-18b7b.firebasestorage.app',
    measurementId: 'G-PND7QG5ZFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrB4M5_xGlxVZqBSVxIjUbpEgXS4E2sNw',
    appId: '1:1046855873659:android:ae012d36204c2bd8155ede',
    messagingSenderId: '1046855873659',
    projectId: 'unirent-18b7b',
    storageBucket: 'unirent-18b7b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARnXj7E2JM-W6JqNM8ZkwxFKagypK0NSE',
    appId: '1:1046855873659:ios:f786ed7a3b04cff0155ede',
    messagingSenderId: '1046855873659',
    projectId: 'unirent-18b7b',
    storageBucket: 'unirent-18b7b.firebasestorage.app',
    androidClientId: '1046855873659-omqqjt9be3ic78u6bs0rlr16sktbqr45.apps.googleusercontent.com',
    iosClientId: '1046855873659-gqqiprvllofesl9c6vav7dmg6l1builp.apps.googleusercontent.com',
    iosBundleId: 'com.example.unirent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARnXj7E2JM-W6JqNM8ZkwxFKagypK0NSE',
    appId: '1:1046855873659:ios:f786ed7a3b04cff0155ede',
    messagingSenderId: '1046855873659',
    projectId: 'unirent-18b7b',
    storageBucket: 'unirent-18b7b.firebasestorage.app',
    iosClientId: '1046855873659-gqqiprvllofesl9c6vav7dmg6l1builp.apps.googleusercontent.com',
    iosBundleId: 'com.example.unirent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAarROnSmiCyYHq__1hp2Ua_Zw7auln7rA',
    appId: '1:1046855873659:web:126d365c39dbca59155ede',
    messagingSenderId: '1046855873659',
    projectId: 'unirent-18b7b',
    authDomain: 'unirent-18b7b.firebaseapp.com',
    storageBucket: 'unirent-18b7b.firebasestorage.app',
    measurementId: 'G-ZGS8LR2JSD',
  );
}
