// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7L8k-XpO6idPrOH6thGkhaqzaLr3XdXs',
    appId: '1:1016985675104:web:5e05f9de751a1e76a82a05',
    messagingSenderId: '1016985675104',
    projectId: 'unirent-342c7',
    authDomain: 'unirent-342c7.firebaseapp.com',
    storageBucket: 'unirent-342c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvMRLMXvg2kXSftMDIHW4k7mENM4bidM',
    appId: '1:1016985675104:android:2ef5250d49407248a82a05',
    messagingSenderId: '1016985675104',
    projectId: 'unirent-342c7',
    storageBucket: 'unirent-342c7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYlFSFKdHap3Wx4IYsuariiqZuV1F0p8',
    appId: '1:1016985675104:ios:1dd99397d675d8b6a82a05',
    messagingSenderId: '1016985675104',
    projectId: 'unirent-342c7',
    storageBucket: 'unirent-342c7.firebasestorage.app',
    iosClientId: '1016985675104-436r04es235r0iu69ut8jjbae3a1hf9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.unirent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfYlFSFKdHap3Wx4IYsuariiqZuV1F0p8',
    appId: '1:1016985675104:ios:1dd99397d675d8b6a82a05',
    messagingSenderId: '1016985675104',
    projectId: 'unirent-342c7',
    storageBucket: 'unirent-342c7.firebasestorage.app',
    iosClientId: '1016985675104-436r04es235r0iu69ut8jjbae3a1hf9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.unirent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7L8k-XpO6idPrOH6thGkhaqzaLr3XdXs',
    appId: '1:1016985675104:web:740765a77471435ba82a05',
    messagingSenderId: '1016985675104',
    projectId: 'unirent-342c7',
    authDomain: 'unirent-342c7.firebaseapp.com',
    storageBucket: 'unirent-342c7.firebasestorage.app',
  );
}
